function F=Fun_b(x,z,bet,fp,fg,tauw,wp,hp,sigmaa,lamb,chi,wg,hg,chig,phi,alph,pm,y,mu,lp,nu)
N=x(1);
Op=x(2);
Og=x(3);
xi=x(4);
sigmab=x(5);

F(1)=z+bet*(fp*Op+fg*Og+(1-fp-fg)*N) ...
     -N;
F(2)=(1-tauw)*wp*hp+sigmaa*nu*log(1-hp)/lamb ...
     +bet*((1-chi)*Op+chi*N) ...
     -Op;
F(3)=(1-tauw)*wg*hg+sigmab*nu*log(1-hg)/lamb ...
     +bet*((1-chig)*Og+chig*N) ...
     -Og;
F(4)=-Op+Og+xi;
F(5)=phi*((1-alph)*pm*y+fp/mu*lp) ...
    +(1-phi)/(1-tauw)*(z-sigmaa*nu*log(1-hp)/lamb+bet*fg*(Og-N)) ...
    -wp*hp;

end